blank_issues_enabled: false
contact_links:
  - name: WEEZOOKA™#5949
    url: https://discord.gg/qbcore
    about: if you need support just add me on discord. can update the script to add whatever but may end up becoming a comission depending on complexity
